inputs:
  app-name:
    description: 'The name of the Android app to test, e.g., JetNews or JetLagged'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run instrumentation tests
      run: |
        ./mill show ${{ inputs.app-name }}.app.androidApk
        ./mill show ${{ inputs.app-name }}.app.createAndroidVirtualDevice
        ./mill --debug show ${{ inputs.app-name }}.app.startAndroidEmulator
        ./mill show ${{ inputs.app-name }}.app.androidTest
        ./mill show ${{ inputs.app-name }}.app.stopAndroidEmulator
      shell: bash

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-jetnews
        path: out/${{ inputs.app-name }}/app/androidTest/testForked.dest/test-report.xml