name: "Publish Test Report"
description: "Publish JUnit test report"

runs:
  using: "composite"
  steps:
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v6
      if: (!cancelled())
      with:
        fail_on_failure: false
        include_passed: false
        detailed_summary: true
        annotate_only: true
        require_tests: false
        report_paths: 'out/**/test-report.xml'
