inputs:
  app-name:
    description: 'The name of the Android app to test, e.g., JetNews or JetLagged'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run instrumentation tests
      run: |
        ./mill show ${{ inputs.app-name }}.androidApk
        ./mill show ${{ inputs.app-name }}.androidTest.androidTestApk
        ./mill show ${{ inputs.app-name }}.createAndroidVirtualDevice
        ./mill --debug show ${{ inputs.app-name }}.startAndroidEmulator
        ./mill show ${{ inputs.app-name }}.androidTest
        ./mill show ${{ inputs.app-name }}.stopAndroidEmulator
      shell: bash