name: Run Tests Reusable

on:
  workflow_call:
    inputs:
      use_custom_mill:
        type: boolean
        required: false
        default: false

jobs:
  android-tests:
    name: Android Tests (${{ matrix.app }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        app: [ JetLagged.app, JetNews.app, Jetsnack.app, Jetchat.app ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-environment
        with:
          use_custom_mill: ${{ inputs.use_custom_mill }}
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: ${{ matrix.app }}
      - uses: ./.github/actions/publish-report
        if: (!cancelled())

  android-run-app:
    name: Android Tests (${{ matrix.app }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        app: [ Reply.app, Jetcaster.mobile, Jetcaster.tv, Jetcaster.wear ]
        include:
          - app: Reply.app
            app-activity: com.example.reply.ui.MainActivity
          - app: Jetcaster.mobile
            app-activity: com.example.jetcaster.ui.MainActivity
          - app: Jetcaster.tv
            app-activity: com.example.jetcaster.tv.MainActivity
          - app: Jetcaster.wear
            app-activity: .MainActivity
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-environment
        with:
          use_custom_mill: ${{ inputs.use_custom_mill }}
      - uses: ./.github/actions/mill-android-run-apps
        with:
          app-name: ${{ matrix.app }}
          app-activity: ${{ matrix.app-activity }}

  android-unit-tests:
    name: Android Unit Tests (${{ matrix.app }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        app: [ Jetcaster.wear ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-environment
        with:
          use_custom_mill: ${{ inputs.use_custom_mill }}
      - uses: ./.github/actions/mill-android-unit-test
        with:
          app-name: ${{ matrix.app }}
      - uses: ./.github/actions/publish-report
        if: (!cancelled())
