name: Test Jetsnack

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  androidTest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: ./.github/actions/android-setup
      - name: Run instrumentation tests
        run: |
          ./mill show Jetsnack.app.androidApk
          ./mill show Jetsnack.app.createAndroidVirtualDevice
          ./mill --debug show Jetsnack.app.startAndroidEmulator
          ./mill show Jetsnack.app.androidTest
          ./mill show Jetsnack.app.stopAndroidEmulator
        shell: bash

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-jetnews
          path: out/Jetsnack/app/androidTest/testForked.dest/test-report.xml
