name: Test Apps

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: test-apps-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-tests:
    name: Android Tests (${{ matrix.app }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        app: [ JetLagged.app, JetNews.app, Jetsnack.app, Jetchat.app ]
    steps:
      - uses: coursier/cache-action@v6
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-setup
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: ${{ matrix.app }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: (!cancelled())
        with:
          fail_on_failure: false
          include_passed: false
          detailed_summary: true
          annotate_only: true
          require_tests: false
          report_paths: 'out/**/test-report.xml'
  android-run-app:
    name: Android Tests (${{ matrix.app }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        app: [ Reply.app, Jetcaster.mobile, Jetcaster.tv, Jetcaster.wear ]
        include:
          - app: Reply.app
            app-activity: com.example.reply.ui.MainActivity
          - app: Jetcaster.mobile
            app-activity: com.example.jetcaster.ui.MainActivity
          - app: Jetcaster.tv
            app-activity: com.example.jetcaster.tv.MainActivity
          - app: Jetcaster.wear
            app-activity: .JetcasterWearApplication
    steps:
      - uses: coursier/cache-action@v6
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-setup
      - uses: ./.github/actions/mill-android-run-apps
        with:
          app-name: ${{ matrix.app }}
          app-activity: ${{ matrix.app-activity }}
