name: Test Apps

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  androidTest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: coursier/cache-action@v6
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: JetLagged
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: JetNews
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: Jetsnack


