name: Test Apps

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  androidTest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: coursier/cache-action@v6
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-setup
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: JetLagged
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: JetNews
      - uses: ./.github/actions/mill-android-test
        with:
          app-name: Jetsnack
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: (!cancelled())
        with:
          fail_on_failure: false
          include_passed: false
          detailed_summary: true
          annotate_only: true
          require_tests: false
          report_paths: 'out/**/test-report.xml'


