name: Test Apps

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: test-apps-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/_run-tests.yaml
